name: Publish Specific Commit

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'The commit SHA to checkout and publish'
        required: true

jobs:
  build_commit:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.COMMIT_SHA }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build With Gradle
        run: ./gradlew build

      - name: Test With Gradle
        run: ./gradlew test

      - name: Publish Build
        run: |
          echo "Publishing build..."
          ./gradlew publish -PmavenRepoUrl=${{ secrets.MAVEN_REPO }}
